---
- hosts: remote
  remote_user: "{{admin_user}}"
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh
  tasks:
    - name: copying
      copy:
        src: ../services/user/jack.service
        dest: /etc/systemd/user
        owner: root
        group: root
    - name: enable linger for audio_user
      command: 'loginctl enable-linger "{{audio_user}}"'

- hosts: remote
  remote_user: "{{audio_user}}"
  gather_facts: no
  connection: ssh
  tasks:
    - name: Enable jack service and ensure it is not masked
      ansible.builtin.systemd:
        name: jack
        enabled: yes
        masked: no
        scope: user
